### ISSUE TITLE
Pick a better name

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/soapbox#3]

**Comment by RobLoach** [comment]
- pulpit
- soapbox

**Comment by RobLoach** [comment]
Soapbox is clean, cool, and under control.

**Comment by derekderaps** [comment]
standing on a soapbox to preach, soapbox derby, all good things!

**Comment by derekderaps** [comment]
PR merged. Next step is rename the actual repo. Over to you, @RobLoach !
